### ISSUE TITLE
refresh workflow failing 

### ISSUE THREAD

**Issue by t-huyeng** [bundesAPI/apis#28]
https://github.com/bundesAPI/apis/actions/runs/3125329528

[![Refresh API list](https://github.com/bundesAPI/apis/actions/workflows/refresh.yml/badge.svg)](https://github.com/bundesAPI/apis/actions/workflows/refresh.yml)
Currently the Workflow is failing with

```
Run node refresh.js
undefined:176
  },
  ^

SyntaxError: Unexpected token } in JSON at position 7830
    at JSON.parse (<anonymous>)
    at main (/home/runner/work/apis/apis/refresh.js:[4]
Error: Process completed with exit code 1.
```

I am not able to recreate this problem locally. If I try `node refresh.js` locally it works fine.

**Comment by t-huyeng** [comment]
https://github.com/t-huyeng/bunddev-apis/actions/runs/3126752686/jobs/5072769151 
Working on my fork. Unsure why. 
Maybe fixed with #29.

**Comment by wirthual** [comment]
This MR was intended to fix this problem. 

https://github.com/bundesAPI/apis/pull/27

Great that you introduce a linter to avoid such errors in future 👍

**Comment by t-huyeng** [comment]
That makes sense. I tried rerunning the action and thought that it would already use the "new" `overrides.json` but apparently it does use the old one. But it should work this night.
